linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace

# output configuration options
output:
# colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gocritic:
    disabled-checks:
      - ifElseChain
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  dogsled:
    max-blank-identifiers: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gosec
        - scopelint
        - ineffassign
    - path: \.go
      linters:
        - goconst
        - nakedret
        - typecheck
        - gofmt

run:
  timeout: 10m
