version: '3.9'

services:
  db:
    image: mariadb:10.3.13
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=rio_services
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: "--character-set-server=utf8mb4 --max-connections=100000"
    ports:
      - "3306:3306"
    logging:
      driver: none
    tmpfs:
      - /var/lib/mysql
