name: ci

on:
  push:
    branches:
      - "**"

concurrency:
  group: branch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:

      - uses: actions/checkout@v3
      
      - name: Run lint
        run: make lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Run unit test
        run: make test-mysql-up

      - name: Post Run unit test
        if: ${{ always() }}
        run: make test-mysql-down
