-- MySQL Script generated by MySQL Workbench
-- Sat Aug  7 13:27:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rio_services
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rio_services
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rio_services` DEFAULT CHARACTER SET utf8 ;
USE `rio_services` ;

-- -----------------------------------------------------
-- Table `rio_services`.`stubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rio_services`.`stubs` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `namespace` VARCHAR(255) NOT NULL DEFAULT '',
  `request` JSON NULL,
  `response` JSON NULL,
  `weight` INT NOT NULL DEFAULT 0,
  `active` INT NOT NULL DEFAULT 0,
  `settings` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rio_services`.`incoming_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rio_services`.`incoming_requests` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `namespace` VARCHAR(255) NOT NULL DEFAULT '',
    `url` LONGTEXT NOT NULL,
    `method` VARCHAR(31) NOT NULL DEFAULT '',
    `header` JSON NULL,
    `body` BLOB NULL,
    `stub_id` BIGINT(20) NOT NULL DEFAULT 0,
    `curl` LONGTEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
